/**
 * Fetch Categories
 */
export const ASYNC_FETCH_CATEGORIES_REQUEST = "ASYNC_FETCH_CATEGORIES_REQUEST";
export const ASYNC_FETCH_CATEGORIES_SUCCESS = "ASYNC_FETCH_CATEGORIES_SUCCESS";
export const ASYNC_FETCH_CATEGORIES_ERROR = "ASYNC_FETCH_CATEGORIES_ERROR";

/**
 * Fetch Jokes
 */
export const ASYNC_FETCH_JOKES_REQUEST = "ASYNC_FETCH_JOKES_REQUEST";
export const ASYNC_FETCH_JOKES_SUCCESS = "ASYNC_FETCH_JOKES_SUCCESS";
export const ASYNC_FETCH_JOKES_ERROR = "ASYNC_FETCH_JOKES_ERROR";
